version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - aws cloudformation package --template-file claimsprocessor.yaml --output-template-file output-claimsprocessor.yaml --s3-bucket octank-healthcare
      - aws cloudformation deploy --template-file output-claimsprocessor.yaml --stack-name OctankClaimsProcessor
artifacts:
  files:
    - target/octank-claims-lambda-1.0-SNAPSHOT.jar
