AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Java+Hibernate Lambda  for claims processing

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  ClaimsProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.octank.claims.main.ClaimsProcessingHandler::handleRequest
      Runtime: java8
      CodeUri: target/octank-claims-lambda-1.0-SNAPSHOT.jar
      MemorySize: 1024
      Role: arn:aws:iam::716664005094:role/microServiceRole
      Timeout: 600
      
      VpcConfig: # For accessing RDS instance
        SecurityGroupIds:
          - sg-0f91a34ea8a021962
        SubnetIds:
          - subnet-09801d6354de7c2ae
          - subnet-0266f93796d5c6e4b
      Environment:
        Variables:
          RDS_HOSTNAME: oa1ltjd7wms0ff3.clfzy7tgfzlq.us-west-2.rds.amazonaws.com:3306
          RDS_DB_NAME: CLAIMS
          RDS_USERNAME: auradmin
          RDS_PASSWORD: auradmin123