AWSTemplateFormatVersion: '2010-09-09'
Description: Java+Hibernate Lambda  for claims processing
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  ClaimsProcessorFunction:
    Properties:
      CodeUri: s3://octank-healthcare/2232c2b91694418e8a08a43b65704e6a
      Environment:
        Variables:
          RDS_DB_NAME: CLAIMS
          RDS_HOSTNAME: oa1ltjd7wms0ff3.clfzy7tgfzlq.us-west-2.rds.amazonaws.com:3306
          RDS_PASSWORD: auradmin123
          RDS_USERNAME: auradmin
      Handler: org.octank.claims.main.ClaimsProcessingHandler::handleRequest
      MemorySize: 1024
      Role: arn:aws:iam::716664005094:role/microServiceRole
      Runtime: java8
      Timeout: 600
      VpcConfig:
        SecurityGroupIds:
        - sg-0f91a34ea8a021962
        SubnetIds:
        - subnet-09801d6354de7c2ae
        - subnet-0266f93796d5c6e4b
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
