package org.octank.claims.model;
// Generated Nov 28, 2018 2:11:05 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClaimProcessingId generated by hbm2java
 */
@Embeddable
public class ClaimProcessingId implements java.io.Serializable {

	private String claimId;
	private Date claimProcessDate;

	public ClaimProcessingId() {
	}

	public ClaimProcessingId(String claimId, Date claimProcessDate) {
		this.claimId = claimId;
		this.claimProcessDate = claimProcessDate;
	}

	@Column(name = "CLAIM_ID", nullable = false, length = 20)
	public String getClaimId() {
		return this.claimId;
	}

	public void setClaimId(String claimId) {
		this.claimId = claimId;
	}

	@Column(name = "CLAIM_PROCESS_DATE", nullable = false, length = 26)
	public Date getClaimProcessDate() {
		return this.claimProcessDate;
	}

	public void setClaimProcessDate(Date claimProcessDate) {
		this.claimProcessDate = claimProcessDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClaimProcessingId))
			return false;
		ClaimProcessingId castOther = (ClaimProcessingId) other;

		return ((this.getClaimId() == castOther.getClaimId()) || (this.getClaimId() != null
				&& castOther.getClaimId() != null && this.getClaimId().equals(castOther.getClaimId())))
				&& ((this.getClaimProcessDate() == castOther.getClaimProcessDate())
						|| (this.getClaimProcessDate() != null && castOther.getClaimProcessDate() != null
								&& this.getClaimProcessDate().equals(castOther.getClaimProcessDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getClaimId() == null ? 0 : this.getClaimId().hashCode());
		result = 37 * result + (getClaimProcessDate() == null ? 0 : this.getClaimProcessDate().hashCode());
		return result;
	}

}
