package org.octank.claims.model;
// Generated Nov 28, 2018 2:11:05 PM by Hibernate Tools 5.2.11.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Claim generated by hbm2java
 */
@Entity
@Table(name = "CLAIM", catalog = "CLAIMS")
public class Claim implements java.io.Serializable {

	private String claimId;
	private String staffId;
	private String claimStatus;
	private String medicalProviderId;
	private String insuranceCompanyId;
	private String patientId;
	private Date updatedDate;
	private BigDecimal amountClaimed;
	private BigDecimal amountPaid;
	private String insurancePolicyNbr;

	public Claim() {
	}

	public Claim(String claimId) {
		this.claimId = claimId;
	}

	public Claim(String claimId, String staffId, String claimStatus, String medicalProviderId,
			String insuranceCompanyId, String patientId, Date updatedDate, BigDecimal amountClaimed,
			BigDecimal amountPaid, String insurancePolicyNbr) {
		this.claimId = claimId;
		this.staffId = staffId;
		this.claimStatus = claimStatus;
		this.medicalProviderId = medicalProviderId;
		this.insuranceCompanyId = insuranceCompanyId;
		this.patientId = patientId;
		this.updatedDate = updatedDate;
		this.amountClaimed = amountClaimed;
		this.amountPaid = amountPaid;
		this.insurancePolicyNbr = insurancePolicyNbr;
	}

	@Id

	@Column(name = "CLAIM_ID", unique = true, nullable = false, length = 20)
	public String getClaimId() {
		return this.claimId;
	}

	public void setClaimId(String claimId) {
		this.claimId = claimId;
	}

	@Column(name = "STAFF_ID", length = 20)
	public String getStaffId() {
		return this.staffId;
	}

	public void setStaffId(String staffId) {
		this.staffId = staffId;
	}

	@Column(name = "CLAIM_STATUS", length = 20)
	public String getClaimStatus() {
		return this.claimStatus;
	}

	public void setClaimStatus(String claimStatus) {
		this.claimStatus = claimStatus;
	}

	@Column(name = "MEDICAL_PROVIDER_ID", length = 20)
	public String getMedicalProviderId() {
		return this.medicalProviderId;
	}

	public void setMedicalProviderId(String medicalProviderId) {
		this.medicalProviderId = medicalProviderId;
	}

	@Column(name = "INSURANCE_COMPANY_ID", length = 20)
	public String getInsuranceCompanyId() {
		return this.insuranceCompanyId;
	}

	public void setInsuranceCompanyId(String insuranceCompanyId) {
		this.insuranceCompanyId = insuranceCompanyId;
	}

	@Column(name = "PATIENT_ID", length = 20)
	public String getPatientId() {
		return this.patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", length = 26)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "AMOUNT_CLAIMED", precision = 10)
	public BigDecimal getAmountClaimed() {
		return this.amountClaimed;
	}

	public void setAmountClaimed(BigDecimal amountClaimed) {
		this.amountClaimed = amountClaimed;
	}

	@Column(name = "AMOUNT_PAID", precision = 10)
	public BigDecimal getAmountPaid() {
		return this.amountPaid;
	}

	public void setAmountPaid(BigDecimal amountPaid) {
		this.amountPaid = amountPaid;
	}

	@Column(name = "INSURANCE_POLICY_NBR", length = 20)
	public String getInsurancePolicyNbr() {
		return this.insurancePolicyNbr;
	}

	public void setInsurancePolicyNbr(String insurancePolicyNbr) {
		this.insurancePolicyNbr = insurancePolicyNbr;
	}

}
