package org.octank.claims.model;
// Generated Nov 28, 2018 2:11:05 PM by Hibernate Tools 5.2.11.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ClaimProcessing generated by hbm2java
 */
@Entity
@Table(name = "CLAIM_PROCESSING", catalog = "CLAIMS")
public class ClaimProcessing implements java.io.Serializable {

	private ClaimProcessingId id;
	private String claimStatus;
	private String patientName;
	private String patientGender;
	private String physicianName;
	private String medicalProviderName;
	private String insuranceCompanyName;
	private BigDecimal amountClaimed;
	private BigDecimal amountPaid;

	public ClaimProcessing() {
	}

	public ClaimProcessing(ClaimProcessingId id) {
		this.id = id;
	}

	public ClaimProcessing(ClaimProcessingId id, String claimStatus, String patientName, String patientGender,
			String physicianName, String medicalProviderName, String insuranceCompanyName, BigDecimal amountClaimed,
			BigDecimal amountPaid) {
		this.id = id;
		this.claimStatus = claimStatus;
		this.patientName = patientName;
		this.patientGender = patientGender;
		this.physicianName = physicianName;
		this.medicalProviderName = medicalProviderName;
		this.insuranceCompanyName = insuranceCompanyName;
		this.amountClaimed = amountClaimed;
		this.amountPaid = amountPaid;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "claimId", column = @Column(name = "CLAIM_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "claimProcessDate", column = @Column(name = "CLAIM_PROCESS_DATE", nullable = false, length = 26)) })
	public ClaimProcessingId getId() {
		return this.id;
	}

	public void setId(ClaimProcessingId id) {
		this.id = id;
	}

	@Column(name = "CLAIM_STATUS", length = 20)
	public String getClaimStatus() {
		return this.claimStatus;
	}

	public void setClaimStatus(String claimStatus) {
		this.claimStatus = claimStatus;
	}

	@Column(name = "PATIENT_NAME", length = 20)
	public String getPatientName() {
		return this.patientName;
	}

	public void setPatientName(String patientName) {
		this.patientName = patientName;
	}

	@Column(name = "PATIENT_GENDER", length = 20)
	public String getPatientGender() {
		return this.patientGender;
	}

	public void setPatientGender(String patientGender) {
		this.patientGender = patientGender;
	}

	@Column(name = "PHYSICIAN_NAME", length = 30)
	public String getPhysicianName() {
		return this.physicianName;
	}

	public void setPhysicianName(String physicianName) {
		this.physicianName = physicianName;
	}

	@Column(name = "MEDICAL_PROVIDER_NAME", length = 30)
	public String getMedicalProviderName() {
		return this.medicalProviderName;
	}

	public void setMedicalProviderName(String medicalProviderName) {
		this.medicalProviderName = medicalProviderName;
	}

	@Column(name = "INSURANCE_COMPANY_NAME", length = 30)
	public String getInsuranceCompanyName() {
		return this.insuranceCompanyName;
	}

	public void setInsuranceCompanyName(String insuranceCompanyName) {
		this.insuranceCompanyName = insuranceCompanyName;
	}

	@Column(name = "AMOUNT_CLAIMED", precision = 10)
	public BigDecimal getAmountClaimed() {
		return this.amountClaimed;
	}

	public void setAmountClaimed(BigDecimal amountClaimed) {
		this.amountClaimed = amountClaimed;
	}

	@Column(name = "AMOUNT_PAID", precision = 10)
	public BigDecimal getAmountPaid() {
		return this.amountPaid;
	}

	public void setAmountPaid(BigDecimal amountPaid) {
		this.amountPaid = amountPaid;
	}

}
