package org.octank.claims.model;
// Generated Nov 28, 2018 2:11:05 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InsuranceCompany generated by hbm2java
 */
@Entity
@Table(name = "INSURANCE_COMPANY", catalog = "CLAIMS")
public class InsuranceCompany implements java.io.Serializable {

	private String insuranceCompanyId;
	private String insuranceCompanyName;
	private String insuranceCompanyAddress;
	private String insuranceCompanyCity;
	private String insuranceCompanyState;
	private String insuranceCompanyZip;
	private String insuranceCompanyCountry;

	public InsuranceCompany() {
	}

	public InsuranceCompany(String insuranceCompanyId) {
		this.insuranceCompanyId = insuranceCompanyId;
	}

	public InsuranceCompany(String insuranceCompanyId, String insuranceCompanyName, String insuranceCompanyAddress,
			String insuranceCompanyCity, String insuranceCompanyState, String insuranceCompanyZip,
			String insuranceCompanyCountry) {
		this.insuranceCompanyId = insuranceCompanyId;
		this.insuranceCompanyName = insuranceCompanyName;
		this.insuranceCompanyAddress = insuranceCompanyAddress;
		this.insuranceCompanyCity = insuranceCompanyCity;
		this.insuranceCompanyState = insuranceCompanyState;
		this.insuranceCompanyZip = insuranceCompanyZip;
		this.insuranceCompanyCountry = insuranceCompanyCountry;
	}

	@Id

	@Column(name = "INSURANCE_COMPANY_ID", unique = true, nullable = false, length = 20)
	public String getInsuranceCompanyId() {
		return this.insuranceCompanyId;
	}

	public void setInsuranceCompanyId(String insuranceCompanyId) {
		this.insuranceCompanyId = insuranceCompanyId;
	}

	@Column(name = "INSURANCE_COMPANY_NAME", length = 30)
	public String getInsuranceCompanyName() {
		return this.insuranceCompanyName;
	}

	public void setInsuranceCompanyName(String insuranceCompanyName) {
		this.insuranceCompanyName = insuranceCompanyName;
	}

	@Column(name = "INSURANCE_COMPANY_ADDRESS", length = 50)
	public String getInsuranceCompanyAddress() {
		return this.insuranceCompanyAddress;
	}

	public void setInsuranceCompanyAddress(String insuranceCompanyAddress) {
		this.insuranceCompanyAddress = insuranceCompanyAddress;
	}

	@Column(name = "INSURANCE_COMPANY_CITY", length = 20)
	public String getInsuranceCompanyCity() {
		return this.insuranceCompanyCity;
	}

	public void setInsuranceCompanyCity(String insuranceCompanyCity) {
		this.insuranceCompanyCity = insuranceCompanyCity;
	}

	@Column(name = "INSURANCE_COMPANY_STATE", length = 20)
	public String getInsuranceCompanyState() {
		return this.insuranceCompanyState;
	}

	public void setInsuranceCompanyState(String insuranceCompanyState) {
		this.insuranceCompanyState = insuranceCompanyState;
	}

	@Column(name = "INSURANCE_COMPANY_ZIP", length = 20)
	public String getInsuranceCompanyZip() {
		return this.insuranceCompanyZip;
	}

	public void setInsuranceCompanyZip(String insuranceCompanyZip) {
		this.insuranceCompanyZip = insuranceCompanyZip;
	}

	@Column(name = "INSURANCE_COMPANY_COUNTRY", length = 20)
	public String getInsuranceCompanyCountry() {
		return this.insuranceCompanyCountry;
	}

	public void setInsuranceCompanyCountry(String insuranceCompanyCountry) {
		this.insuranceCompanyCountry = insuranceCompanyCountry;
	}

}
