package org.octank.claims.model;
// Generated Nov 28, 2018 2:11:05 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MedicalProvider generated by hbm2java
 */
@Entity
@Table(name = "MEDICAL_PROVIDER", catalog = "CLAIMS")
public class MedicalProvider implements java.io.Serializable {

	private String medicalProviderId;
	private String medicalProviderName;
	private String medicalProviderAddress;
	private String medicalProviderCity;
	private String medicalProviderState;
	private String medicalProviderZip;
	private String medicalProviderCountry;

	public MedicalProvider() {
	}

	public MedicalProvider(String medicalProviderId) {
		this.medicalProviderId = medicalProviderId;
	}

	public MedicalProvider(String medicalProviderId, String medicalProviderName, String medicalProviderAddress,
			String medicalProviderCity, String medicalProviderState, String medicalProviderZip,
			String medicalProviderCountry) {
		this.medicalProviderId = medicalProviderId;
		this.medicalProviderName = medicalProviderName;
		this.medicalProviderAddress = medicalProviderAddress;
		this.medicalProviderCity = medicalProviderCity;
		this.medicalProviderState = medicalProviderState;
		this.medicalProviderZip = medicalProviderZip;
		this.medicalProviderCountry = medicalProviderCountry;
	}

	@Id

	@Column(name = "MEDICAL_PROVIDER_ID", unique = true, nullable = false, length = 20)
	public String getMedicalProviderId() {
		return this.medicalProviderId;
	}

	public void setMedicalProviderId(String medicalProviderId) {
		this.medicalProviderId = medicalProviderId;
	}

	@Column(name = "MEDICAL_PROVIDER_NAME", length = 30)
	public String getMedicalProviderName() {
		return this.medicalProviderName;
	}

	public void setMedicalProviderName(String medicalProviderName) {
		this.medicalProviderName = medicalProviderName;
	}

	@Column(name = "MEDICAL_PROVIDER_ADDRESS", length = 50)
	public String getMedicalProviderAddress() {
		return this.medicalProviderAddress;
	}

	public void setMedicalProviderAddress(String medicalProviderAddress) {
		this.medicalProviderAddress = medicalProviderAddress;
	}

	@Column(name = "MEDICAL_PROVIDER_CITY", length = 20)
	public String getMedicalProviderCity() {
		return this.medicalProviderCity;
	}

	public void setMedicalProviderCity(String medicalProviderCity) {
		this.medicalProviderCity = medicalProviderCity;
	}

	@Column(name = "MEDICAL_PROVIDER_STATE", length = 20)
	public String getMedicalProviderState() {
		return this.medicalProviderState;
	}

	public void setMedicalProviderState(String medicalProviderState) {
		this.medicalProviderState = medicalProviderState;
	}

	@Column(name = "MEDICAL_PROVIDER_ZIP", length = 20)
	public String getMedicalProviderZip() {
		return this.medicalProviderZip;
	}

	public void setMedicalProviderZip(String medicalProviderZip) {
		this.medicalProviderZip = medicalProviderZip;
	}

	@Column(name = "MEDICAL_PROVIDER_COUNTRY", length = 20)
	public String getMedicalProviderCountry() {
		return this.medicalProviderCountry;
	}

	public void setMedicalProviderCountry(String medicalProviderCountry) {
		this.medicalProviderCountry = medicalProviderCountry;
	}

}
