package org.octank.claims.model;
// Generated Nov 28, 2018 2:11:05 PM by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Staff generated by hbm2java
 */
@Entity
@Table(name = "STAFF", catalog = "CLAIMS")
public class Staff implements java.io.Serializable {

	private String staffId;
	private String staffCategory;
	private String gender;
	private String staffName;
	private Date staffBirthDate;

	public Staff() {
	}

	public Staff(String staffId) {
		this.staffId = staffId;
	}

	public Staff(String staffId, String staffCategory, String gender, String staffName, Date staffBirthDate) {
		this.staffId = staffId;
		this.staffCategory = staffCategory;
		this.gender = gender;
		this.staffName = staffName;
		this.staffBirthDate = staffBirthDate;
	}

	@Id

	@Column(name = "STAFF_ID", unique = true, nullable = false, length = 20)
	public String getStaffId() {
		return this.staffId;
	}

	public void setStaffId(String staffId) {
		this.staffId = staffId;
	}

	@Column(name = "STAFF_CATEGORY", length = 20)
	public String getStaffCategory() {
		return this.staffCategory;
	}

	public void setStaffCategory(String staffCategory) {
		this.staffCategory = staffCategory;
	}

	@Column(name = "GENDER", length = 20)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "STAFF_NAME", length = 20)
	public String getStaffName() {
		return this.staffName;
	}

	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "STAFF_BIRTH_DATE", length = 26)
	public Date getStaffBirthDate() {
		return this.staffBirthDate;
	}

	public void setStaffBirthDate(Date staffBirthDate) {
		this.staffBirthDate = staffBirthDate;
	}

}
